### ISSUE TITLE
Coolify Installation

### ISSUE THREAD

**Issue by amolkittur** [Serendipity2-0/TradeManV1#98]
# Coolify Installation in Server

## Description
We need to install Coolify on our server so that we can host/manage all our server in a single place.

## Installation Command
The following command should be used to install Coolify:

```bash
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
```

## Tasks
- [ ] Run the installation command
- [ ] Verify successful installation
- [ ] Configure Coolify settings as needed
- [ ] Test basic functionality

## Additional Notes
- Ensure you have necessary permissions to run the installation script
- Document any issues encountered during installation
- Update relevant documentation to reflect the new Coolify installation

## Resources
- [Coolify Documentation](https://coolify.io/docs)
- [Coolify GitHub Repository](https://github.com/coollabsio/coolify)

**Comment by amolkittur** [comment]
Got this error when i excuted the installation command 


```
Serendipity-2:~ root# curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
mkdir: /data: Read-only file system
```


This error is caused because root filesystem is mounted as read-only.
This situation is typically associated with macOS's security features, particularly on newer Macs with Apple Silicon (M1, M2, etc.) or T2 security chips. The system volume is "sealed" and mounted as read-only to prevent modifications that could compromise system integrity.



So i'll be checking the coolify community if they have any solutions for it

**Comment by amolkittur** [comment]
I am trying to run coolify locally (npm run dev)i got a error saying APP_URL undefined.

then i tried using the docker compose there was no proper documentation on how to install it in MacOS. So now ill try it installing in windows device.
